// The user's crontab on disk, read and written through the `crontab` binary
// without a shell (execFile / spawn + stdin).
//
//   mutate(fn) ─► lock ─► crontab -l ─► fn(doc) ─► unchanged? → done, nothing written
//                              │                    dryRun?   → { before, after }
//                              │                    expectedHash ≠ current? → CrontabConflictError
//                              ▼
//        backup(before) → crontab - (after) → crontab -l → equal? → done
//                                                        └ no → crontab - (before), throw
//
// Backups: $PITASKER_STATE_DIR/crontab-backups (default ~/.local/state/pitasker),
// one file per write, newest 50 kept.
// Tests: refuses to run without FAKE_CRONTAB_FILE when VITEST or PITASKER_E2E
// is set, so a test can never reach the real crontab.
import { execFile, spawn } from "child_process";
import { createHash } from "crypto";
import fs from "fs";
import os from "os";
import path from "path";
import { parseCrontab, serializeCrontab, withFinalNewline, type CrontabDoc } from "./document";

export const BACKUP_KEEP = 50;
const BACKUP_RE = /^crontab-\d{8}T\d{9}Z(?:-\d+)?\.txt$/;

export class CrontabConflictError extends Error {
  status = 409;
  constructor() {
    super("The crontab changed since it was shown. Reload and review the change again.");
  }
}

export class CrontabWriteError extends Error {
  status = 502;
}

export function crontabBin(): string {
  const bin = process.env.PITASKER_CRONTAB_BIN || "crontab";
  if ((process.env.VITEST || process.env.PITASKER_E2E) && !process.env.FAKE_CRONTAB_FILE) {
    throw new Error("refusing to run crontab in a test without FAKE_CRONTAB_FILE (a fake crontab on PATH)");
  }
  return bin;
}

export function stateDir(): string {
  return process.env.PITASKER_STATE_DIR || path.join(os.homedir(), ".local", "state", "pitasker");
}

export function backupDir(): string {
  return path.join(stateDir(), "crontab-backups");
}

export const hashText = (text: string) => createHash("sha256").update(text).digest("hex");

/** Debian/Vixie may prefix `crontab -l` with a "DO NOT EDIT" header; it is not part of the content. */
export function stripListingHeader(text: string): string {
  return text.replace(/^# DO NOT EDIT THIS FILE[^\n]*\n# \(\S+ installed on [^\n]*\n# \(Cron version[^\n]*\n/, "");
}

export function readCrontabText(): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(crontabBin(), ["-l"], { timeout: 15_000, maxBuffer: 4 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (!err) return resolve(stripListingHeader(stdout));
      if (/no crontab for/i.test(String(stderr))) return resolve("");
      reject(new Error(`crontab -l failed: ${String(stderr).trim() || err.message}`));
    });
  });
}

export function writeCrontabText(text: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(crontabBin(), ["-"], { stdio: ["pipe", "ignore", "pipe"] });
    let stderr = "";
    const timer = setTimeout(() => child.kill("SIGKILL"), 15_000);
    child.stderr.on("data", (d) => (stderr += d));
    child.on("error", (e) => {
      clearTimeout(timer);
      reject(e);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code === 0) resolve();
      else reject(new CrontabWriteError(`crontab - failed (exit ${code}): ${stderr.trim()}`));
    });
    child.stdin.end(text);
  });
}

function stamp(d = new Date()): string {
  return d.toISOString().replace(/[-:]/g, "").replace(".", "");
}

export function saveBackup(text: string): string {
  const dir = backupDir();
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  let name = `crontab-${stamp()}.txt`;
  for (let i = 1; fs.existsSync(path.join(dir, name)); i++) name = `crontab-${stamp()}-${i}.txt`;
  fs.writeFileSync(path.join(dir, name), text, { mode: 0o600 });
  pruneBackups();
  return name;
}

export type BackupInfo = { name: string; size: number; createdAt: string };

export function listBackups(): BackupInfo[] {
  const dir = backupDir();
  if (!fs.existsSync(dir)) return [];
  // Newest first: by timestamp, then by the -N suffix two writes in one millisecond get.
  const key = (n: string) => {
    const m = /^crontab-(\d{8}T\d{9}Z)(?:-(\d+))?\.txt$/.exec(n)!;
    return `${m[1]}-${(m[2] ?? "0").padStart(6, "0")}`;
  };
  return fs
    .readdirSync(dir)
    .filter((n) => BACKUP_RE.test(n))
    .sort((a, b) => (key(a) < key(b) ? 1 : key(a) > key(b) ? -1 : 0))
    .map((name) => {
      const st = fs.statSync(path.join(dir, name));
      return { name, size: st.size, createdAt: st.mtime.toISOString() };
    });
}

export function pruneBackups(keep = BACKUP_KEEP): void {
  const dir = backupDir();
  for (const b of listBackups().slice(keep)) fs.rmSync(path.join(dir, b.name), { force: true });
}

export function readBackup(name: string): string {
  if (!BACKUP_RE.test(name)) throw Object.assign(new Error("Invalid backup name"), { status: 400 });
  const file = path.join(backupDir(), name);
  if (!fs.existsSync(file)) throw Object.assign(new Error("Backup not found"), { status: 404 });
  return fs.readFileSync(file, "utf8");
}

export type MutateResult = {
  changed: boolean;
  written: boolean;
  before: string;
  after: string;
  beforeHash: string;
  backup?: string;
};

export type MutateOptions = { dryRun?: boolean; expectedHash?: string };

let queue: Promise<unknown> = Promise.resolve();
/** Serialise every crontab read-modify-write in this process. */
function locked<T>(fn: () => Promise<T>): Promise<T> {
  const run = queue.then(fn, fn);
  queue = run.catch(() => undefined);
  return run;
}

export async function readCrontab(): Promise<{ text: string; hash: string; doc: CrontabDoc }> {
  const text = await readCrontabText();
  return { text, hash: hashText(text), doc: parseCrontab(text) };
}

/**
 * Apply `fn` to the current crontab and write the result — only when it
 * changed, with a backup first and a read-back check after.
 */
export function mutateCrontab(fn: (doc: CrontabDoc, text: string) => CrontabDoc | string, opts: MutateOptions = {}): Promise<MutateResult> {
  return locked(async () => {
    const before = await readCrontabText();
    const beforeHash = hashText(before);
    if (opts.expectedHash && opts.expectedHash !== beforeHash) throw new CrontabConflictError();
    const out = fn(parseCrontab(before), before);
    const produced = typeof out === "string" ? out : serializeCrontab(out);
    const after = produced === before ? before : withFinalNewline(produced);
    const base = { before, after, beforeHash };
    if (after === before) return { ...base, changed: false, written: false };
    if (opts.dryRun) return { ...base, changed: true, written: false };

    const backup = saveBackup(before);
    try {
      await writeCrontabText(after);
    } catch (e) {
      throw e instanceof CrontabWriteError ? e : new CrontabWriteError(`crontab write failed: ${(e as Error).message}`);
    }
    const check = await readCrontabText().catch(() => null);
    if (check !== after) {
      await writeCrontabText(before).catch(() => undefined);
      throw new CrontabWriteError(`crontab read-back did not match what was written; restored the previous crontab (backup ${backup})`);
    }
    return { ...base, changed: true, written: true, backup };
  });
}
