import { useLayoutEffect, useRef, type ReactNode, type RefObject } from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

/*
 * The one confirmation dialog (E7). Not generated by shadcn — PiDeck's own.
 *   open ─► focus lands on Cancel (never on the risky button)
 *   Esc / overlay / Cancel ─► onOpenChange(false), nothing runs
 *   Confirm ─► onConfirm(); while `pending` both buttons are disabled and
 *              the dialog can't be dismissed (the request can't be undone)
 *   close ─► focus returns to whatever had it when the dialog opened (the
 *            trigger), or to `returnFocusRef` when that element is gone
 *            (e.g. the palette). Radix alone only restores a DialogTrigger;
 *            these dialogs open from state.
 */
export function ConfirmDialog({
  open,
  onOpenChange,
  title,
  description,
  confirmLabel,
  cancelLabel = "Cancel",
  destructive = false,
  pending = false,
  pendingLabel,
  onConfirm,
  returnFocusRef,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  description: ReactNode;
  confirmLabel: string;
  cancelLabel?: string;
  destructive?: boolean;
  pending?: boolean;
  pendingLabel?: string;
  onConfirm: () => void;
  returnFocusRef?: RefObject<HTMLElement | null>;
}) {
  const cancelRef = useRef<HTMLButtonElement>(null);
  const opener = useRef<HTMLElement | null>(null);
  // Layout effect: runs before Radix's FocusScope moves focus into the dialog.
  useLayoutEffect(() => {
    if (open) opener.current = document.activeElement as HTMLElement | null;
  }, [open]);
  const change = (next: boolean) => {
    if (!next && pending) return; // can't dismiss mid-request
    onOpenChange(next);
  };

  return (
    <DialogPrimitive.Root open={open} onOpenChange={change}>
      <DialogPrimitive.Portal>
        <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/60" />
        <DialogPrimitive.Content
          data-testid="confirm-dialog"
          className="fixed left-1/2 top-1/2 z-50 grid w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 gap-4 rounded-lg border border-pi-border bg-pi-card p-6 text-pi-text shadow-lg"
          onOpenAutoFocus={(e) => {
            e.preventDefault();
            cancelRef.current?.focus();
          }}
          onCloseAutoFocus={(e) => {
            e.preventDefault();
            const back = returnFocusRef?.current ?? (opener.current?.isConnected ? opener.current : null);
            back?.focus();
          }}
        >
          <DialogPrimitive.Title className="text-lg font-semibold">{title}</DialogPrimitive.Title>
          <DialogPrimitive.Description className="text-sm text-pi-text-muted">{description}</DialogPrimitive.Description>
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
            <button
              ref={cancelRef}
              type="button"
              disabled={pending}
              onClick={() => change(false)}
              className="inline-flex h-9 items-center justify-center rounded-md border border-pi-border px-4 text-sm hover:bg-pi-card-hover disabled:opacity-50"
            >
              {cancelLabel}
            </button>
            <button
              type="button"
              disabled={pending}
              aria-busy={pending || undefined}
              onClick={onConfirm}
              className={cn(
                "inline-flex h-9 items-center justify-center gap-2 rounded-md px-4 text-sm font-medium disabled:opacity-70",
                destructive
                  ? "bg-red-700 text-pi-on-accent hover:bg-red-800"
                  : "bg-pi-accent text-pi-on-accent hover:bg-pi-accent-hover",
              )}
            >
              {pending && <Loader2 className="h-4 w-4 animate-spin" aria-hidden />}
              {pending ? (pendingLabel ?? confirmLabel) : confirmLabel}
            </button>
          </div>
        </DialogPrimitive.Content>
      </DialogPrimitive.Portal>
    </DialogPrimitive.Root>
  );
}
