import fs from "fs";
import path from "path";
import { beforeEach, describe, expect, it } from "vitest";
import { upsertJob } from "../../server/crontab/document";
import {
  BACKUP_KEEP,
  CrontabConflictError,
  CrontabWriteError,
  backupDir,
  crontabBin,
  hashText,
  listBackups,
  mutateCrontab,
  readBackup,
  readCrontab,
  readCrontabText,
  saveBackup,
} from "../../server/crontab/store";

const CURATED = fs.readFileSync(path.join(__dirname, "..", "fixtures", "crontab.curated"), "utf8");
const file = () => process.env.FAKE_CRONTAB_FILE!;
const log = () => (fs.existsSync(process.env.FAKE_CRONTAB_LOG!) ? fs.readFileSync(process.env.FAKE_CRONTAB_LOG!, "utf8") : "");

beforeEach(() => {
  fs.rmSync(file(), { force: true });
  fs.rmSync(backupDir(), { recursive: true, force: true });
  process.env.FAKE_CRONTAB_LOG = `${file()}.log`;
  fs.rmSync(process.env.FAKE_CRONTAB_LOG, { force: true });
  delete process.env.FAKE_CRONTAB_FAIL_WRITE;
  delete process.env.FAKE_CRONTAB_MANGLE;
});

describe("safety", () => {
  it("uses the fake crontab in tests", () => {
    expect(crontabBin()).toContain("pitasker-unit-");
  });

  it("refuses to run without FAKE_CRONTAB_FILE under VITEST", () => {
    const saved = process.env.FAKE_CRONTAB_FILE;
    delete process.env.FAKE_CRONTAB_FILE;
    try {
      expect(() => crontabBin()).toThrow(/refusing/);
    } finally {
      process.env.FAKE_CRONTAB_FILE = saved;
    }
  });
});

describe("reading", () => {
  it("treats 'no crontab' as empty", async () => {
    expect(await readCrontabText()).toBe("");
  });

  it("returns the crontab byte-for-byte", async () => {
    fs.writeFileSync(file(), CURATED);
    const r = await readCrontab();
    expect(r.text).toBe(CURATED);
    expect(r.hash).toBe(hashText(CURATED));
  });

  it("drops a Debian 'DO NOT EDIT' listing header", async () => {
    fs.writeFileSync(
      file(),
      "# DO NOT EDIT THIS FILE - edit the master and reinstall.\n# (- installed on Tue Sep 30 10:00:00 2026)\n# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)\n0 * * * * /bin/x\n",
    );
    expect(await readCrontabText()).toBe("0 * * * * /bin/x\n");
  });
});

describe("mutateCrontab", () => {
  it("writes nothing (no backup, no crontab -) when nothing changes", async () => {
    fs.writeFileSync(file(), CURATED);
    const r = await mutateCrontab((doc) => doc);
    expect(r).toMatchObject({ changed: false, written: false });
    expect(log()).not.toContain("crontab -\n");
    expect(listBackups()).toEqual([]);
    expect(fs.readFileSync(file(), "utf8")).toBe(CURATED);
  });

  it("backs up, writes, and reads back", async () => {
    fs.writeFileSync(file(), CURATED);
    const r = await mutateCrontab((doc) => upsertJob(doc, { id: "n1", schedule: "@hourly", command: "/bin/n" }));
    expect(r.written).toBe(true);
    expect(fs.readFileSync(file(), "utf8")).toBe(`${CURATED}# PITASKER_ID:n1\n@hourly /bin/n\n`);
    const backups = listBackups();
    expect(backups).toHaveLength(1);
    expect(readBackup(backups[0].name)).toBe(CURATED);
    expect(fs.statSync(path.join(backupDir(), backups[0].name)).mode & 0o777).toBe(0o600);
  });

  it("dry run returns before/after without writing", async () => {
    fs.writeFileSync(file(), CURATED);
    const r = await mutateCrontab((doc) => upsertJob(doc, { id: "n1", schedule: "@hourly", command: "/bin/n" }), { dryRun: true });
    expect(r).toMatchObject({ changed: true, written: false, before: CURATED });
    expect(r.after).toContain("@hourly /bin/n");
    expect(fs.readFileSync(file(), "utf8")).toBe(CURATED);
  });

  it("refuses when the crontab changed since it was shown", async () => {
    fs.writeFileSync(file(), CURATED);
    await expect(mutateCrontab((d) => d, { expectedHash: hashText("something else") })).rejects.toBeInstanceOf(CrontabConflictError);
  });

  it("adds the final newline cron needs", async () => {
    await mutateCrontab(() => "0 * * * * /bin/a");
    expect(fs.readFileSync(file(), "utf8")).toBe("0 * * * * /bin/a\n");
  });

  it("restores the previous crontab when the read-back differs", async () => {
    fs.writeFileSync(file(), CURATED);
    process.env.FAKE_CRONTAB_MANGLE = "1";
    await expect(mutateCrontab((doc) => upsertJob(doc, { id: "n1", schedule: "@hourly", command: "/bin/n" }))).rejects.toThrow(/restored/);
    delete process.env.FAKE_CRONTAB_MANGLE;
    // the restore itself went through the mangling fake once more; what matters is that it was attempted with the original text
    expect(fs.readFileSync(file(), "utf8").startsWith(CURATED)).toBe(true);
    expect(fs.readFileSync(file(), "utf8")).not.toContain("/bin/n");
  });

  it("reports a failed write and leaves the crontab alone", async () => {
    fs.writeFileSync(file(), CURATED);
    process.env.FAKE_CRONTAB_FAIL_WRITE = "1";
    await expect(mutateCrontab(() => "0 * * * * /bin/a\n")).rejects.toBeInstanceOf(CrontabWriteError);
    expect(fs.readFileSync(file(), "utf8")).toBe(CURATED);
  });

  it("serialises concurrent writers (no lost update)", async () => {
    await Promise.all(
      Array.from({ length: 5 }, (_, i) => mutateCrontab((doc) => upsertJob(doc, { id: `c${i}`, schedule: "@hourly", command: `/bin/c${i}` }))),
    );
    const text = fs.readFileSync(file(), "utf8");
    for (let i = 0; i < 5; i++) expect(text).toContain(`/bin/c${i}`);
  });
});

describe("backups", () => {
  it(`keeps the newest ${BACKUP_KEEP}`, () => {
    for (let i = 0; i < BACKUP_KEEP + 5; i++) saveBackup(`v${i}\n`);
    const list = listBackups();
    expect(list).toHaveLength(BACKUP_KEEP);
    expect(readBackup(list[0].name)).toBe(`v${BACKUP_KEEP + 4}\n`);
  });

  it("orders backups made in the same millisecond correctly", () => {
    fs.mkdirSync(backupDir(), { recursive: true });
    for (const [n, t] of [["crontab-20260930T010203004Z.txt", "a"], ["crontab-20260930T010203004Z-1.txt", "b"], ["crontab-20260930T010203004Z-2.txt", "c"]]) fs.writeFileSync(path.join(backupDir(), n), t);
    expect(listBackups().map((b) => readBackup(b.name))).toEqual(["c", "b", "a"]);
  });

  it("rejects path tricks in backup names", () => {
    expect(() => readBackup("../../etc/passwd")).toThrow(/Invalid/);
  });
});
